#!/bin/bash
# generated by Git for Windows
echo
echo -e $YELLOW"In .BASH_PROFILE"$ATTR_RESET

test -f ~/.profile && . ~/.profile
#test -f ~/.bashrc && . ~/.bashrc

echo -e $YELLOW"Out of .BASH_PROFILE"$ATTR_RESETE
